from __future__ import annotations

from datetime import date

from app.market.schemas import MarketDataRow, MarketSource, SourceStatus


TODAY = date.today().isoformat()


def fixture_rows() -> list[MarketDataRow]:
    return [
        MarketDataRow(source_name="Nornickel production reports", source_url="https://www.nornickel.com/investors/reports-and-results/", date_accessed=TODAY, company_or_country="Nornickel", commodity="nickel", metric="production", period="2023", value=209, unit="kt", confidence="medium", notes="Demo fixture for stable offline presentation.", raw_evidence="Nornickel annual production table style: nickel output by year, kt."),
        MarketDataRow(source_name="Nornickel production reports", source_url="https://www.nornickel.com/investors/reports-and-results/", date_accessed=TODAY, company_or_country="Nornickel", commodity="nickel", metric="production", period="2024", value=205, unit="kt", confidence="medium", notes="Demo fixture for stable offline presentation.", raw_evidence="Nickel production latest annual period, kt."),
        MarketDataRow(source_name="Nornickel production reports", source_url="https://www.nornickel.com/investors/reports-and-results/", date_accessed=TODAY, company_or_country="Nornickel", commodity="copper", metric="production", period="2023", value=425, unit="kt", confidence="medium", notes="Demo fixture for stable offline presentation.", raw_evidence="Copper production annual table, kt."),
        MarketDataRow(source_name="Nornickel production reports", source_url="https://www.nornickel.com/investors/reports-and-results/", date_accessed=TODAY, company_or_country="Nornickel", commodity="copper", metric="production", period="2024", value=433, unit="kt", confidence="medium", notes="Demo fixture for stable offline presentation.", raw_evidence="Copper production latest annual period, kt."),
        MarketDataRow(source_name="Nornickel production reports", source_url="https://www.nornickel.com/investors/reports-and-results/", date_accessed=TODAY, company_or_country="Nornickel", commodity="palladium", metric="production", period="2023", value=2692, unit="koz", confidence="medium", notes="Demo fixture for stable offline presentation.", raw_evidence="Palladium production annual table, thousand ounces."),
        MarketDataRow(source_name="Nornickel production reports", source_url="https://www.nornickel.com/investors/reports-and-results/", date_accessed=TODAY, company_or_country="Nornickel", commodity="palladium", metric="production", period="2024", value=2762, unit="koz", confidence="medium", notes="Demo fixture for stable offline presentation.", raw_evidence="Palladium production latest annual period, koz."),
        MarketDataRow(source_name="Nornickel production reports", source_url="https://www.nornickel.com/investors/reports-and-results/", date_accessed=TODAY, company_or_country="Nornickel", commodity="platinum", metric="production", period="2023", value=664, unit="koz", confidence="medium", notes="Demo fixture for stable offline presentation.", raw_evidence="Platinum production annual table, thousand ounces."),
        MarketDataRow(source_name="Nornickel production reports", source_url="https://www.nornickel.com/investors/reports-and-results/", date_accessed=TODAY, company_or_country="Nornickel", commodity="platinum", metric="production", period="2024", value=667, unit="koz", confidence="medium", notes="Demo fixture for stable offline presentation.", raw_evidence="Platinum production latest annual period, koz."),
        MarketDataRow(source_name="Nornickel production reports", source_url="https://nornickel.com/news-and-media/press-releases-and-news/nornickel-reports-full-year-2024-audited-consolidated-ifrs-financial-results/", date_accessed=TODAY, company_or_country="Nornickel", commodity="company financials", metric="revenue", period="2024", value=12.5, unit="USD bn", confidence="high", notes="IFRS 2024 revenue; useful as a business baseline for nickel/copper/PGM exposure.", raw_evidence="Revenue decreased 13% y-o-y to USD 12.5 billion in 2024."),
        MarketDataRow(source_name="World Steel Association data", source_url="https://worldsteel.org/data/", date_accessed=TODAY, company_or_country="China", commodity="steel", metric="production", period="2024", value=1005, unit="Mt", confidence="medium", notes="Demo fixture for country comparison.", raw_evidence="Crude steel production by country, Mt."),
        MarketDataRow(source_name="World Steel Association data", source_url="https://worldsteel.org/data/", date_accessed=TODAY, company_or_country="India", commodity="steel", metric="production", period="2024", value=149, unit="Mt", confidence="medium", notes="Demo fixture for country comparison.", raw_evidence="Crude steel production by country, Mt."),
        MarketDataRow(source_name="World Steel Association data", source_url="https://worldsteel.org/data/", date_accessed=TODAY, company_or_country="Russia", commodity="steel", metric="production", period="2024", value=71, unit="Mt", confidence="medium", notes="Demo fixture for country comparison.", raw_evidence="Crude steel production by country, Mt."),
        MarketDataRow(source_name="World Steel Association data", source_url="https://worldsteel.org/data/", date_accessed=TODAY, company_or_country="Turkey", commodity="steel", metric="production", period="2024", value=37, unit="Mt", confidence="medium", notes="Demo fixture for country comparison.", raw_evidence="Crude steel production by country, Mt."),
        MarketDataRow(source_name="International Aluminium Institute statistics", source_url="https://international-aluminium.org/statistics/", date_accessed=TODAY, company_or_country="China", commodity="aluminium", metric="production", period="2024", value=43.4, unit="Mt", confidence="medium", notes="Demo fixture for regional aluminium overview.", raw_evidence="Primary aluminium production by region, Mt."),
        MarketDataRow(source_name="International Aluminium Institute statistics", source_url="https://international-aluminium.org/statistics/", date_accessed=TODAY, company_or_country="GCC", commodity="aluminium", metric="production", period="2024", value=6.4, unit="Mt", confidence="medium", notes="Demo fixture for regional aluminium overview.", raw_evidence="Primary aluminium production by region, Mt."),
        MarketDataRow(source_name="International Aluminium Institute statistics", source_url="https://international-aluminium.org/statistics/", date_accessed=TODAY, company_or_country="Europe", commodity="aluminium", metric="production", period="2024", value=7.0, unit="Mt", confidence="medium", notes="Demo fixture for regional aluminium overview.", raw_evidence="Primary aluminium production by region, Mt."),
        MarketDataRow(source_name="International Aluminium Institute statistics", source_url="https://international-aluminium.org/statistics/", date_accessed=TODAY, company_or_country="North America", commodity="aluminium", metric="production", period="2024", value=3.8, unit="Mt", confidence="medium", notes="Demo fixture for regional aluminium overview.", raw_evidence="Primary aluminium production by region, Mt."),
        MarketDataRow(source_name="USGS Mineral Commodity Summaries", source_url="https://www.usgs.gov/centers/national-minerals-information-center/mineral-commodity-summaries", date_accessed=TODAY, company_or_country="Indonesia", commodity="nickel", metric="production", period="2024", value=2200, unit="kt", confidence="medium", notes="Demo fixture for nickel country ranking.", raw_evidence="Mine production by country, kt contained nickel."),
        MarketDataRow(source_name="USGS Mineral Commodity Summaries", source_url="https://www.usgs.gov/centers/national-minerals-information-center/mineral-commodity-summaries", date_accessed=TODAY, company_or_country="Philippines", commodity="nickel", metric="production", period="2024", value=330, unit="kt", confidence="medium", notes="Demo fixture for nickel country ranking.", raw_evidence="Mine production by country, kt contained nickel."),
        MarketDataRow(source_name="USGS Mineral Commodity Summaries", source_url="https://www.usgs.gov/centers/national-minerals-information-center/mineral-commodity-summaries", date_accessed=TODAY, company_or_country="Russia", commodity="nickel", metric="production", period="2024", value=220, unit="kt", confidence="medium", notes="Demo fixture for nickel country ranking.", raw_evidence="Mine production by country, kt contained nickel."),
        MarketDataRow(source_name="USGS Mineral Commodity Summaries", source_url="https://www.usgs.gov/centers/national-minerals-information-center/mineral-commodity-summaries", date_accessed=TODAY, company_or_country="New Caledonia", commodity="nickel", metric="production", period="2024", value=160, unit="kt", confidence="medium", notes="Demo fixture for nickel country ranking.", raw_evidence="Mine production by country, kt contained nickel."),
        MarketDataRow(source_name="RUSAL operating results", source_url="https://rusal.ru/en/investors/results-and-reports/", date_accessed=TODAY, company_or_country="RUSAL", commodity="aluminium", metric="production", period="2024", value=3.8, unit="Mt", confidence="medium", notes="Demo fixture for company production.", raw_evidence="Aluminium production operating result, Mt."),
        MarketDataRow(source_name="RUSAL operating results", source_url="https://rusal.ru/en/investors/results-and-reports/", date_accessed=TODAY, company_or_country="RUSAL", commodity="alumina", metric="production", period="2024", value=5.0, unit="Mt", confidence="medium", notes="Demo fixture for company production.", raw_evidence="Alumina production operating result, Mt."),
        MarketDataRow(source_name="RUSAL operating results", source_url="https://rusal.ru/en/investors/financial-stat/annual-reports/", date_accessed=TODAY, company_or_country="RUSAL", commodity="company financials", metric="revenue", period="2024", value=12.082, unit="USD bn", confidence="high", notes="Annual report / financial statements baseline for aluminium business scale.", raw_evidence="Total revenue for 2024: USD 12,082 million."),
        MarketDataRow(source_name="Severstal operating results", source_url="https://www.akm.ru/eng/news/severstal-s-revenue-increased-by-14-in-2024/", date_accessed=TODAY, company_or_country="Severstal", commodity="company financials", metric="revenue", period="2024", value=829.779, unit="RUB bn", confidence="high", notes="Public 2024 financial result; RUB values should not be merged with USD rows.", raw_evidence="Revenue in 2024 increased by 14% to RUB 829.779 billion."),
        MarketDataRow(source_name="Severstal operating results", source_url="https://www.steelorbis.com/steel-news/latest-news/severstals-sales-revenues-up-14-in-2024-significant-investments-planned-for-2025-1377174.htm", date_accessed=TODAY, company_or_country="Severstal", commodity="steel", metric="sales", period="2024", value=10.85, unit="Mt", confidence="medium", notes="Steel product sales volume for company-scale comparison.", raw_evidence="Steel sales amounted to 10.85 million tonnes in 2024."),
        MarketDataRow(source_name="MMK operating results", source_url="https://www.steelorbis.com/steel-news/latest-news/russias-mmk-posts-lower-net-profit-in-2024-1384505.htm", date_accessed=TODAY, company_or_country="MMK", commodity="company financials", metric="revenue", period="2024", value=768.47, unit="RUB bn", confidence="medium", notes="Public 2024 financial result; use as market context with source caveat.", raw_evidence="Revenue rose to RUB 768.47 billion in 2024."),
        MarketDataRow(source_name="MMK operating results", source_url="https://interfax.com/newsroom/top-stories/109334/", date_accessed=TODAY, company_or_country="MMK", commodity="steel", metric="sales", period="2024", value=10.622, unit="Mt", confidence="medium", notes="Steel product sales volume for company-scale comparison.", raw_evidence="Sales dropped to 10.622 million tonnes in 2024."),
        MarketDataRow(source_name="Water treatment techno-economic demo ranges", source_url="local://demo/water-treatment-techno-economic-ranges", date_accessed=TODAY, company_or_country="Обратный осмос (RO)", commodity="water treatment", metric="energy", period="demo", value="0.8-2.5", unit="кВт·ч/м3", confidence="medium", notes="Shortlist для снижения сухого остатка до ~1000 мг/дм3; требует предочистки от жесткости, железа и взвесей.", raw_evidence="Demo engineering range: RO OPEX обычно определяется электроэнергией, мембранами, реагентами CIP и утилизацией концентрата."),
        MarketDataRow(source_name="Water treatment techno-economic demo ranges", source_url="local://demo/water-treatment-techno-economic-ranges", date_accessed=TODAY, company_or_country="Обратный осмос (RO)", commodity="water treatment", metric="reagents", period="demo", value="medium", unit="antiscalant/CIP", confidence="medium", notes="Антискалант и периодическая химическая промывка; критичны Ca/Mg и сульфаты.", raw_evidence="Demo engineering driver: scaling risk grows with sulfate, calcium and magnesium load."),
        MarketDataRow(source_name="Water treatment techno-economic demo ranges", source_url="local://demo/water-treatment-techno-economic-ranges", date_accessed=TODAY, company_or_country="Нанофильтрация (NF)", commodity="water treatment", metric="energy", period="demo", value="0.4-1.5", unit="кВт·ч/м3", confidence="medium", notes="Хороша для снижения жесткости и сульфатов; по Na/Cl может потребоваться RO/EDR после NF.", raw_evidence="Demo engineering range: NF часто используется как стадия частичного обессоливания или предочистка перед RO."),
        MarketDataRow(source_name="Water treatment techno-economic demo ranges", source_url="local://demo/water-treatment-techno-economic-ranges", date_accessed=TODAY, company_or_country="Электродиализ / EDR", commodity="water treatment", metric="energy", period="demo", value="0.5-2.0", unit="кВт·ч/м3", confidence="medium", notes="Конкурентен для солоноватой воды; энергозатраты растут с солесодержанием, нужна проверка по sulfate/chloride balance.", raw_evidence="Demo engineering driver: EDR cost scales with removed salt load and stack replacement."),
        MarketDataRow(source_name="Water treatment techno-economic demo ranges", source_url="local://demo/water-treatment-techno-economic-ranges", date_accessed=TODAY, company_or_country="Ионный обмен", commodity="water treatment", metric="reagents", period="demo", value="high", unit="NaCl/кислота/щелочь", confidence="medium", notes="Рационален как polishing-ступень; полное обессоливание больших расходов дает высокий расход регенерантов и солевой сток.", raw_evidence="Demo engineering driver: reagent OPEX and brine disposal dominate at high salinity."),
        MarketDataRow(source_name="Water treatment techno-economic demo ranges", source_url="local://demo/water-treatment-techno-economic-ranges", date_accessed=TODAY, company_or_country="Известково-содовое умягчение + фильтрация", commodity="water treatment", metric="reagents", period="demo", value="medium-high", unit="известь/сода/коагулянт", confidence="medium", notes="Снимает Ca/Mg и часть сульфатов, но не решает Na/Cl; лучше как предочистка перед мембранами.", raw_evidence="Demo engineering driver: sludge handling and reagent logistics are key cost drivers."),
        MarketDataRow(source_name="Water treatment techno-economic demo ranges", source_url="local://demo/water-treatment-techno-economic-ranges", date_accessed=TODAY, company_or_country="Выпаривание / MVR / ZLD", commodity="water treatment", metric="energy", period="demo", value="8-20", unit="кВт·ч/м3", confidence="medium", notes="Технически закрывает высокий TDS и концентрат, но обычно имеет максимальные CAPEX/OPEX; рассматривать для хвостового рассола/ZLD.", raw_evidence="Demo engineering driver: thermal concentration is reserved for reject brine or zero liquid discharge cases."),
    ]


def load_rows_for_source(source: MarketSource, *, demo_mode: bool = True) -> tuple[list[MarketDataRow], SourceStatus]:
    if not demo_mode:
        return [], SourceStatus(
            source_id=source.source_id,
            source_name=source.source_name,
            source_url=source.source_url,
            status="unavailable",
            rows_loaded=0,
            message="Live source fetch is intentionally disabled in this demo-safe build.",
        )

    rows = [row for row in fixture_rows() if row.source_name == source.source_name]
    return rows, SourceStatus(
        source_id=source.source_id,
        source_name=source.source_name,
        source_url=source.source_url,
        status="fallback",
        rows_loaded=len(rows),
        message="Loaded small built-in demo fixture; no network request was made.",
    )
